# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            distribution: 'corretto' # See 'Supported distributions' for available options
            java-version: '17'
      - uses: carlosperate/download-file-action@v2
        name: download-coverage
        with:
          file-url: 'https://onetest-opensource-oss.oss-us-west-1.aliyuncs.com/onetest/coverage/jacoco.xml'
          file-name: 'jacoco.xml'
      - run: |
          ls
          pwd
      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
            coverage_results_path: '${{ github.workspace }}/jacoco.xml'
            coverage_report_title: 'Test coverage results'
            coverage_report_name: 'Test coverage results'
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_only_summary: true
